// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: clinks/v1/clinks.proto

package clinksv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/besartmorina/clinks/server/proto/clinks/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ClinksServiceName is the fully-qualified name of the ClinksService service.
	ClinksServiceName = "clinks.v1.ClinksService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ClinksServiceLoginProcedure is the fully-qualified name of the ClinksService's Login RPC.
	ClinksServiceLoginProcedure = "/clinks.v1.ClinksService/Login"
	// ClinksServiceLoginSuperAdminProcedure is the fully-qualified name of the ClinksService's
	// LoginSuperAdmin RPC.
	ClinksServiceLoginSuperAdminProcedure = "/clinks.v1.ClinksService/LoginSuperAdmin"
	// ClinksServiceRegisterProcedure is the fully-qualified name of the ClinksService's Register RPC.
	ClinksServiceRegisterProcedure = "/clinks.v1.ClinksService/Register"
	// ClinksServiceLogoutProcedure is the fully-qualified name of the ClinksService's Logout RPC.
	ClinksServiceLogoutProcedure = "/clinks.v1.ClinksService/Logout"
	// ClinksServiceGetSessionProcedure is the fully-qualified name of the ClinksService's GetSession
	// RPC.
	ClinksServiceGetSessionProcedure = "/clinks.v1.ClinksService/GetSession"
	// ClinksServiceSwitchTenantProcedure is the fully-qualified name of the ClinksService's
	// SwitchTenant RPC.
	ClinksServiceSwitchTenantProcedure = "/clinks.v1.ClinksService/SwitchTenant"
	// ClinksServiceCreateInvitationProcedure is the fully-qualified name of the ClinksService's
	// CreateInvitation RPC.
	ClinksServiceCreateInvitationProcedure = "/clinks.v1.ClinksService/CreateInvitation"
	// ClinksServiceAcceptInvitationProcedure is the fully-qualified name of the ClinksService's
	// AcceptInvitation RPC.
	ClinksServiceAcceptInvitationProcedure = "/clinks.v1.ClinksService/AcceptInvitation"
	// ClinksServiceGetLanguagesProcedure is the fully-qualified name of the ClinksService's
	// GetLanguages RPC.
	ClinksServiceGetLanguagesProcedure = "/clinks.v1.ClinksService/GetLanguages"
	// ClinksServiceGetTranslationsProcedure is the fully-qualified name of the ClinksService's
	// GetTranslations RPC.
	ClinksServiceGetTranslationsProcedure = "/clinks.v1.ClinksService/GetTranslations"
	// ClinksServiceListTenantsProcedure is the fully-qualified name of the ClinksService's ListTenants
	// RPC.
	ClinksServiceListTenantsProcedure = "/clinks.v1.ClinksService/ListTenants"
	// ClinksServiceCreateTenantProcedure is the fully-qualified name of the ClinksService's
	// CreateTenant RPC.
	ClinksServiceCreateTenantProcedure = "/clinks.v1.ClinksService/CreateTenant"
	// ClinksServiceListManagedLanguagesProcedure is the fully-qualified name of the ClinksService's
	// ListManagedLanguages RPC.
	ClinksServiceListManagedLanguagesProcedure = "/clinks.v1.ClinksService/ListManagedLanguages"
	// ClinksServiceSaveLanguageProcedure is the fully-qualified name of the ClinksService's
	// SaveLanguage RPC.
	ClinksServiceSaveLanguageProcedure = "/clinks.v1.ClinksService/SaveLanguage"
	// ClinksServiceSaveTranslationProcedure is the fully-qualified name of the ClinksService's
	// SaveTranslation RPC.
	ClinksServiceSaveTranslationProcedure = "/clinks.v1.ClinksService/SaveTranslation"
	// ClinksServiceListAuditEventsProcedure is the fully-qualified name of the ClinksService's
	// ListAuditEvents RPC.
	ClinksServiceListAuditEventsProcedure = "/clinks.v1.ClinksService/ListAuditEvents"
	// ClinksServiceListUsersProcedure is the fully-qualified name of the ClinksService's ListUsers RPC.
	ClinksServiceListUsersProcedure = "/clinks.v1.ClinksService/ListUsers"
	// ClinksServiceGetUserProcedure is the fully-qualified name of the ClinksService's GetUser RPC.
	ClinksServiceGetUserProcedure = "/clinks.v1.ClinksService/GetUser"
	// ClinksServiceListInvitationsProcedure is the fully-qualified name of the ClinksService's
	// ListInvitations RPC.
	ClinksServiceListInvitationsProcedure = "/clinks.v1.ClinksService/ListInvitations"
	// ClinksServiceRevokeInvitationProcedure is the fully-qualified name of the ClinksService's
	// RevokeInvitation RPC.
	ClinksServiceRevokeInvitationProcedure = "/clinks.v1.ClinksService/RevokeInvitation"
	// ClinksServiceGetSystemStatsProcedure is the fully-qualified name of the ClinksService's
	// GetSystemStats RPC.
	ClinksServiceGetSystemStatsProcedure = "/clinks.v1.ClinksService/GetSystemStats"
)

// ClinksServiceClient is a client for the clinks.v1.ClinksService service.
type ClinksServiceClient interface {
	Login(context.Context, *connect.Request[v1.CredentialsRequest]) (*connect.Response[v1.Session], error)
	LoginSuperAdmin(context.Context, *connect.Request[v1.CredentialsRequest]) (*connect.Response[v1.Session], error)
	Register(context.Context, *connect.Request[v1.RegisterRequest]) (*connect.Response[v1.Session], error)
	Logout(context.Context, *connect.Request[v1.Empty]) (*connect.Response[v1.Empty], error)
	GetSession(context.Context, *connect.Request[v1.Empty]) (*connect.Response[v1.Session], error)
	SwitchTenant(context.Context, *connect.Request[v1.SwitchTenantRequest]) (*connect.Response[v1.Session], error)
	CreateInvitation(context.Context, *connect.Request[v1.CreateInvitationRequest]) (*connect.Response[v1.Invitation], error)
	AcceptInvitation(context.Context, *connect.Request[v1.AcceptInvitationRequest]) (*connect.Response[v1.Session], error)
	GetLanguages(context.Context, *connect.Request[v1.Empty]) (*connect.Response[v1.LanguagesResponse], error)
	GetTranslations(context.Context, *connect.Request[v1.GetTranslationsRequest]) (*connect.Response[v1.TranslationsResponse], error)
	ListTenants(context.Context, *connect.Request[v1.Empty]) (*connect.Response[v1.TenantsResponse], error)
	CreateTenant(context.Context, *connect.Request[v1.CreateTenantRequest]) (*connect.Response[v1.Tenant], error)
	ListManagedLanguages(context.Context, *connect.Request[v1.Empty]) (*connect.Response[v1.LanguagesResponse], error)
	SaveLanguage(context.Context, *connect.Request[v1.Language]) (*connect.Response[v1.Empty], error)
	SaveTranslation(context.Context, *connect.Request[v1.ScopedTranslation]) (*connect.Response[v1.Empty], error)
	ListAuditEvents(context.Context, *connect.Request[v1.ListAuditEventsRequest]) (*connect.Response[v1.AuditEventsResponse], error)
	ListUsers(context.Context, *connect.Request[v1.ListUsersRequest]) (*connect.Response[v1.ListUsersResponse], error)
	GetUser(context.Context, *connect.Request[v1.GetUserRequest]) (*connect.Response[v1.UserDetail], error)
	ListInvitations(context.Context, *connect.Request[v1.ListInvitationsRequest]) (*connect.Response[v1.ListInvitationsResponse], error)
	RevokeInvitation(context.Context, *connect.Request[v1.RevokeInvitationRequest]) (*connect.Response[v1.Empty], error)
	GetSystemStats(context.Context, *connect.Request[v1.Empty]) (*connect.Response[v1.SystemStats], error)
}

// NewClinksServiceClient constructs a client for the clinks.v1.ClinksService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewClinksServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ClinksServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	clinksServiceMethods := v1.File_clinks_v1_clinks_proto.Services().ByName("ClinksService").Methods()
	return &clinksServiceClient{
		login: connect.NewClient[v1.CredentialsRequest, v1.Session](
			httpClient,
			baseURL+ClinksServiceLoginProcedure,
			connect.WithSchema(clinksServiceMethods.ByName("Login")),
			connect.WithClientOptions(opts...),
		),
		loginSuperAdmin: connect.NewClient[v1.CredentialsRequest, v1.Session](
			httpClient,
			baseURL+ClinksServiceLoginSuperAdminProcedure,
			connect.WithSchema(clinksServiceMethods.ByName("LoginSuperAdmin")),
			connect.WithClientOptions(opts...),
		),
		register: connect.NewClient[v1.RegisterRequest, v1.Session](
			httpClient,
			baseURL+ClinksServiceRegisterProcedure,
			connect.WithSchema(clinksServiceMethods.ByName("Register")),
			connect.WithClientOptions(opts...),
		),
		logout: connect.NewClient[v1.Empty, v1.Empty](
			httpClient,
			baseURL+ClinksServiceLogoutProcedure,
			connect.WithSchema(clinksServiceMethods.ByName("Logout")),
			connect.WithClientOptions(opts...),
		),
		getSession: connect.NewClient[v1.Empty, v1.Session](
			httpClient,
			baseURL+ClinksServiceGetSessionProcedure,
			connect.WithSchema(clinksServiceMethods.ByName("GetSession")),
			connect.WithClientOptions(opts...),
		),
		switchTenant: connect.NewClient[v1.SwitchTenantRequest, v1.Session](
			httpClient,
			baseURL+ClinksServiceSwitchTenantProcedure,
			connect.WithSchema(clinksServiceMethods.ByName("SwitchTenant")),
			connect.WithClientOptions(opts...),
		),
		createInvitation: connect.NewClient[v1.CreateInvitationRequest, v1.Invitation](
			httpClient,
			baseURL+ClinksServiceCreateInvitationProcedure,
			connect.WithSchema(clinksServiceMethods.ByName("CreateInvitation")),
			connect.WithClientOptions(opts...),
		),
		acceptInvitation: connect.NewClient[v1.AcceptInvitationRequest, v1.Session](
			httpClient,
			baseURL+ClinksServiceAcceptInvitationProcedure,
			connect.WithSchema(clinksServiceMethods.ByName("AcceptInvitation")),
			connect.WithClientOptions(opts...),
		),
		getLanguages: connect.NewClient[v1.Empty, v1.LanguagesResponse](
			httpClient,
			baseURL+ClinksServiceGetLanguagesProcedure,
			connect.WithSchema(clinksServiceMethods.ByName("GetLanguages")),
			connect.WithClientOptions(opts...),
		),
		getTranslations: connect.NewClient[v1.GetTranslationsRequest, v1.TranslationsResponse](
			httpClient,
			baseURL+ClinksServiceGetTranslationsProcedure,
			connect.WithSchema(clinksServiceMethods.ByName("GetTranslations")),
			connect.WithClientOptions(opts...),
		),
		listTenants: connect.NewClient[v1.Empty, v1.TenantsResponse](
			httpClient,
			baseURL+ClinksServiceListTenantsProcedure,
			connect.WithSchema(clinksServiceMethods.ByName("ListTenants")),
			connect.WithClientOptions(opts...),
		),
		createTenant: connect.NewClient[v1.CreateTenantRequest, v1.Tenant](
			httpClient,
			baseURL+ClinksServiceCreateTenantProcedure,
			connect.WithSchema(clinksServiceMethods.ByName("CreateTenant")),
			connect.WithClientOptions(opts...),
		),
		listManagedLanguages: connect.NewClient[v1.Empty, v1.LanguagesResponse](
			httpClient,
			baseURL+ClinksServiceListManagedLanguagesProcedure,
			connect.WithSchema(clinksServiceMethods.ByName("ListManagedLanguages")),
			connect.WithClientOptions(opts...),
		),
		saveLanguage: connect.NewClient[v1.Language, v1.Empty](
			httpClient,
			baseURL+ClinksServiceSaveLanguageProcedure,
			connect.WithSchema(clinksServiceMethods.ByName("SaveLanguage")),
			connect.WithClientOptions(opts...),
		),
		saveTranslation: connect.NewClient[v1.ScopedTranslation, v1.Empty](
			httpClient,
			baseURL+ClinksServiceSaveTranslationProcedure,
			connect.WithSchema(clinksServiceMethods.ByName("SaveTranslation")),
			connect.WithClientOptions(opts...),
		),
		listAuditEvents: connect.NewClient[v1.ListAuditEventsRequest, v1.AuditEventsResponse](
			httpClient,
			baseURL+ClinksServiceListAuditEventsProcedure,
			connect.WithSchema(clinksServiceMethods.ByName("ListAuditEvents")),
			connect.WithClientOptions(opts...),
		),
		listUsers: connect.NewClient[v1.ListUsersRequest, v1.ListUsersResponse](
			httpClient,
			baseURL+ClinksServiceListUsersProcedure,
			connect.WithSchema(clinksServiceMethods.ByName("ListUsers")),
			connect.WithClientOptions(opts...),
		),
		getUser: connect.NewClient[v1.GetUserRequest, v1.UserDetail](
			httpClient,
			baseURL+ClinksServiceGetUserProcedure,
			connect.WithSchema(clinksServiceMethods.ByName("GetUser")),
			connect.WithClientOptions(opts...),
		),
		listInvitations: connect.NewClient[v1.ListInvitationsRequest, v1.ListInvitationsResponse](
			httpClient,
			baseURL+ClinksServiceListInvitationsProcedure,
			connect.WithSchema(clinksServiceMethods.ByName("ListInvitations")),
			connect.WithClientOptions(opts...),
		),
		revokeInvitation: connect.NewClient[v1.RevokeInvitationRequest, v1.Empty](
			httpClient,
			baseURL+ClinksServiceRevokeInvitationProcedure,
			connect.WithSchema(clinksServiceMethods.ByName("RevokeInvitation")),
			connect.WithClientOptions(opts...),
		),
		getSystemStats: connect.NewClient[v1.Empty, v1.SystemStats](
			httpClient,
			baseURL+ClinksServiceGetSystemStatsProcedure,
			connect.WithSchema(clinksServiceMethods.ByName("GetSystemStats")),
			connect.WithClientOptions(opts...),
		),
	}
}

// clinksServiceClient implements ClinksServiceClient.
type clinksServiceClient struct {
	login                *connect.Client[v1.CredentialsRequest, v1.Session]
	loginSuperAdmin      *connect.Client[v1.CredentialsRequest, v1.Session]
	register             *connect.Client[v1.RegisterRequest, v1.Session]
	logout               *connect.Client[v1.Empty, v1.Empty]
	getSession           *connect.Client[v1.Empty, v1.Session]
	switchTenant         *connect.Client[v1.SwitchTenantRequest, v1.Session]
	createInvitation     *connect.Client[v1.CreateInvitationRequest, v1.Invitation]
	acceptInvitation     *connect.Client[v1.AcceptInvitationRequest, v1.Session]
	getLanguages         *connect.Client[v1.Empty, v1.LanguagesResponse]
	getTranslations      *connect.Client[v1.GetTranslationsRequest, v1.TranslationsResponse]
	listTenants          *connect.Client[v1.Empty, v1.TenantsResponse]
	createTenant         *connect.Client[v1.CreateTenantRequest, v1.Tenant]
	listManagedLanguages *connect.Client[v1.Empty, v1.LanguagesResponse]
	saveLanguage         *connect.Client[v1.Language, v1.Empty]
	saveTranslation      *connect.Client[v1.ScopedTranslation, v1.Empty]
	listAuditEvents      *connect.Client[v1.ListAuditEventsRequest, v1.AuditEventsResponse]
	listUsers            *connect.Client[v1.ListUsersRequest, v1.ListUsersResponse]
	getUser              *connect.Client[v1.GetUserRequest, v1.UserDetail]
	listInvitations      *connect.Client[v1.ListInvitationsRequest, v1.ListInvitationsResponse]
	revokeInvitation     *connect.Client[v1.RevokeInvitationRequest, v1.Empty]
	getSystemStats       *connect.Client[v1.Empty, v1.SystemStats]
}

// Login calls clinks.v1.ClinksService.Login.
func (c *clinksServiceClient) Login(ctx context.Context, req *connect.Request[v1.CredentialsRequest]) (*connect.Response[v1.Session], error) {
	return c.login.CallUnary(ctx, req)
}

// LoginSuperAdmin calls clinks.v1.ClinksService.LoginSuperAdmin.
func (c *clinksServiceClient) LoginSuperAdmin(ctx context.Context, req *connect.Request[v1.CredentialsRequest]) (*connect.Response[v1.Session], error) {
	return c.loginSuperAdmin.CallUnary(ctx, req)
}

// Register calls clinks.v1.ClinksService.Register.
func (c *clinksServiceClient) Register(ctx context.Context, req *connect.Request[v1.RegisterRequest]) (*connect.Response[v1.Session], error) {
	return c.register.CallUnary(ctx, req)
}

// Logout calls clinks.v1.ClinksService.Logout.
func (c *clinksServiceClient) Logout(ctx context.Context, req *connect.Request[v1.Empty]) (*connect.Response[v1.Empty], error) {
	return c.logout.CallUnary(ctx, req)
}

// GetSession calls clinks.v1.ClinksService.GetSession.
func (c *clinksServiceClient) GetSession(ctx context.Context, req *connect.Request[v1.Empty]) (*connect.Response[v1.Session], error) {
	return c.getSession.CallUnary(ctx, req)
}

// SwitchTenant calls clinks.v1.ClinksService.SwitchTenant.
func (c *clinksServiceClient) SwitchTenant(ctx context.Context, req *connect.Request[v1.SwitchTenantRequest]) (*connect.Response[v1.Session], error) {
	return c.switchTenant.CallUnary(ctx, req)
}

// CreateInvitation calls clinks.v1.ClinksService.CreateInvitation.
func (c *clinksServiceClient) CreateInvitation(ctx context.Context, req *connect.Request[v1.CreateInvitationRequest]) (*connect.Response[v1.Invitation], error) {
	return c.createInvitation.CallUnary(ctx, req)
}

// AcceptInvitation calls clinks.v1.ClinksService.AcceptInvitation.
func (c *clinksServiceClient) AcceptInvitation(ctx context.Context, req *connect.Request[v1.AcceptInvitationRequest]) (*connect.Response[v1.Session], error) {
	return c.acceptInvitation.CallUnary(ctx, req)
}

// GetLanguages calls clinks.v1.ClinksService.GetLanguages.
func (c *clinksServiceClient) GetLanguages(ctx context.Context, req *connect.Request[v1.Empty]) (*connect.Response[v1.LanguagesResponse], error) {
	return c.getLanguages.CallUnary(ctx, req)
}

// GetTranslations calls clinks.v1.ClinksService.GetTranslations.
func (c *clinksServiceClient) GetTranslations(ctx context.Context, req *connect.Request[v1.GetTranslationsRequest]) (*connect.Response[v1.TranslationsResponse], error) {
	return c.getTranslations.CallUnary(ctx, req)
}

// ListTenants calls clinks.v1.ClinksService.ListTenants.
func (c *clinksServiceClient) ListTenants(ctx context.Context, req *connect.Request[v1.Empty]) (*connect.Response[v1.TenantsResponse], error) {
	return c.listTenants.CallUnary(ctx, req)
}

// CreateTenant calls clinks.v1.ClinksService.CreateTenant.
func (c *clinksServiceClient) CreateTenant(ctx context.Context, req *connect.Request[v1.CreateTenantRequest]) (*connect.Response[v1.Tenant], error) {
	return c.createTenant.CallUnary(ctx, req)
}

// ListManagedLanguages calls clinks.v1.ClinksService.ListManagedLanguages.
func (c *clinksServiceClient) ListManagedLanguages(ctx context.Context, req *connect.Request[v1.Empty]) (*connect.Response[v1.LanguagesResponse], error) {
	return c.listManagedLanguages.CallUnary(ctx, req)
}

// SaveLanguage calls clinks.v1.ClinksService.SaveLanguage.
func (c *clinksServiceClient) SaveLanguage(ctx context.Context, req *connect.Request[v1.Language]) (*connect.Response[v1.Empty], error) {
	return c.saveLanguage.CallUnary(ctx, req)
}

// SaveTranslation calls clinks.v1.ClinksService.SaveTranslation.
func (c *clinksServiceClient) SaveTranslation(ctx context.Context, req *connect.Request[v1.ScopedTranslation]) (*connect.Response[v1.Empty], error) {
	return c.saveTranslation.CallUnary(ctx, req)
}

// ListAuditEvents calls clinks.v1.ClinksService.ListAuditEvents.
func (c *clinksServiceClient) ListAuditEvents(ctx context.Context, req *connect.Request[v1.ListAuditEventsRequest]) (*connect.Response[v1.AuditEventsResponse], error) {
	return c.listAuditEvents.CallUnary(ctx, req)
}

// ListUsers calls clinks.v1.ClinksService.ListUsers.
func (c *clinksServiceClient) ListUsers(ctx context.Context, req *connect.Request[v1.ListUsersRequest]) (*connect.Response[v1.ListUsersResponse], error) {
	return c.listUsers.CallUnary(ctx, req)
}

// GetUser calls clinks.v1.ClinksService.GetUser.
func (c *clinksServiceClient) GetUser(ctx context.Context, req *connect.Request[v1.GetUserRequest]) (*connect.Response[v1.UserDetail], error) {
	return c.getUser.CallUnary(ctx, req)
}

// ListInvitations calls clinks.v1.ClinksService.ListInvitations.
func (c *clinksServiceClient) ListInvitations(ctx context.Context, req *connect.Request[v1.ListInvitationsRequest]) (*connect.Response[v1.ListInvitationsResponse], error) {
	return c.listInvitations.CallUnary(ctx, req)
}

// RevokeInvitation calls clinks.v1.ClinksService.RevokeInvitation.
func (c *clinksServiceClient) RevokeInvitation(ctx context.Context, req *connect.Request[v1.RevokeInvitationRequest]) (*connect.Response[v1.Empty], error) {
	return c.revokeInvitation.CallUnary(ctx, req)
}

// GetSystemStats calls clinks.v1.ClinksService.GetSystemStats.
func (c *clinksServiceClient) GetSystemStats(ctx context.Context, req *connect.Request[v1.Empty]) (*connect.Response[v1.SystemStats], error) {
	return c.getSystemStats.CallUnary(ctx, req)
}

// ClinksServiceHandler is an implementation of the clinks.v1.ClinksService service.
type ClinksServiceHandler interface {
	Login(context.Context, *connect.Request[v1.CredentialsRequest]) (*connect.Response[v1.Session], error)
	LoginSuperAdmin(context.Context, *connect.Request[v1.CredentialsRequest]) (*connect.Response[v1.Session], error)
	Register(context.Context, *connect.Request[v1.RegisterRequest]) (*connect.Response[v1.Session], error)
	Logout(context.Context, *connect.Request[v1.Empty]) (*connect.Response[v1.Empty], error)
	GetSession(context.Context, *connect.Request[v1.Empty]) (*connect.Response[v1.Session], error)
	SwitchTenant(context.Context, *connect.Request[v1.SwitchTenantRequest]) (*connect.Response[v1.Session], error)
	CreateInvitation(context.Context, *connect.Request[v1.CreateInvitationRequest]) (*connect.Response[v1.Invitation], error)
	AcceptInvitation(context.Context, *connect.Request[v1.AcceptInvitationRequest]) (*connect.Response[v1.Session], error)
	GetLanguages(context.Context, *connect.Request[v1.Empty]) (*connect.Response[v1.LanguagesResponse], error)
	GetTranslations(context.Context, *connect.Request[v1.GetTranslationsRequest]) (*connect.Response[v1.TranslationsResponse], error)
	ListTenants(context.Context, *connect.Request[v1.Empty]) (*connect.Response[v1.TenantsResponse], error)
	CreateTenant(context.Context, *connect.Request[v1.CreateTenantRequest]) (*connect.Response[v1.Tenant], error)
	ListManagedLanguages(context.Context, *connect.Request[v1.Empty]) (*connect.Response[v1.LanguagesResponse], error)
	SaveLanguage(context.Context, *connect.Request[v1.Language]) (*connect.Response[v1.Empty], error)
	SaveTranslation(context.Context, *connect.Request[v1.ScopedTranslation]) (*connect.Response[v1.Empty], error)
	ListAuditEvents(context.Context, *connect.Request[v1.ListAuditEventsRequest]) (*connect.Response[v1.AuditEventsResponse], error)
	ListUsers(context.Context, *connect.Request[v1.ListUsersRequest]) (*connect.Response[v1.ListUsersResponse], error)
	GetUser(context.Context, *connect.Request[v1.GetUserRequest]) (*connect.Response[v1.UserDetail], error)
	ListInvitations(context.Context, *connect.Request[v1.ListInvitationsRequest]) (*connect.Response[v1.ListInvitationsResponse], error)
	RevokeInvitation(context.Context, *connect.Request[v1.RevokeInvitationRequest]) (*connect.Response[v1.Empty], error)
	GetSystemStats(context.Context, *connect.Request[v1.Empty]) (*connect.Response[v1.SystemStats], error)
}

// NewClinksServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewClinksServiceHandler(svc ClinksServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	clinksServiceMethods := v1.File_clinks_v1_clinks_proto.Services().ByName("ClinksService").Methods()
	clinksServiceLoginHandler := connect.NewUnaryHandler(
		ClinksServiceLoginProcedure,
		svc.Login,
		connect.WithSchema(clinksServiceMethods.ByName("Login")),
		connect.WithHandlerOptions(opts...),
	)
	clinksServiceLoginSuperAdminHandler := connect.NewUnaryHandler(
		ClinksServiceLoginSuperAdminProcedure,
		svc.LoginSuperAdmin,
		connect.WithSchema(clinksServiceMethods.ByName("LoginSuperAdmin")),
		connect.WithHandlerOptions(opts...),
	)
	clinksServiceRegisterHandler := connect.NewUnaryHandler(
		ClinksServiceRegisterProcedure,
		svc.Register,
		connect.WithSchema(clinksServiceMethods.ByName("Register")),
		connect.WithHandlerOptions(opts...),
	)
	clinksServiceLogoutHandler := connect.NewUnaryHandler(
		ClinksServiceLogoutProcedure,
		svc.Logout,
		connect.WithSchema(clinksServiceMethods.ByName("Logout")),
		connect.WithHandlerOptions(opts...),
	)
	clinksServiceGetSessionHandler := connect.NewUnaryHandler(
		ClinksServiceGetSessionProcedure,
		svc.GetSession,
		connect.WithSchema(clinksServiceMethods.ByName("GetSession")),
		connect.WithHandlerOptions(opts...),
	)
	clinksServiceSwitchTenantHandler := connect.NewUnaryHandler(
		ClinksServiceSwitchTenantProcedure,
		svc.SwitchTenant,
		connect.WithSchema(clinksServiceMethods.ByName("SwitchTenant")),
		connect.WithHandlerOptions(opts...),
	)
	clinksServiceCreateInvitationHandler := connect.NewUnaryHandler(
		ClinksServiceCreateInvitationProcedure,
		svc.CreateInvitation,
		connect.WithSchema(clinksServiceMethods.ByName("CreateInvitation")),
		connect.WithHandlerOptions(opts...),
	)
	clinksServiceAcceptInvitationHandler := connect.NewUnaryHandler(
		ClinksServiceAcceptInvitationProcedure,
		svc.AcceptInvitation,
		connect.WithSchema(clinksServiceMethods.ByName("AcceptInvitation")),
		connect.WithHandlerOptions(opts...),
	)
	clinksServiceGetLanguagesHandler := connect.NewUnaryHandler(
		ClinksServiceGetLanguagesProcedure,
		svc.GetLanguages,
		connect.WithSchema(clinksServiceMethods.ByName("GetLanguages")),
		connect.WithHandlerOptions(opts...),
	)
	clinksServiceGetTranslationsHandler := connect.NewUnaryHandler(
		ClinksServiceGetTranslationsProcedure,
		svc.GetTranslations,
		connect.WithSchema(clinksServiceMethods.ByName("GetTranslations")),
		connect.WithHandlerOptions(opts...),
	)
	clinksServiceListTenantsHandler := connect.NewUnaryHandler(
		ClinksServiceListTenantsProcedure,
		svc.ListTenants,
		connect.WithSchema(clinksServiceMethods.ByName("ListTenants")),
		connect.WithHandlerOptions(opts...),
	)
	clinksServiceCreateTenantHandler := connect.NewUnaryHandler(
		ClinksServiceCreateTenantProcedure,
		svc.CreateTenant,
		connect.WithSchema(clinksServiceMethods.ByName("CreateTenant")),
		connect.WithHandlerOptions(opts...),
	)
	clinksServiceListManagedLanguagesHandler := connect.NewUnaryHandler(
		ClinksServiceListManagedLanguagesProcedure,
		svc.ListManagedLanguages,
		connect.WithSchema(clinksServiceMethods.ByName("ListManagedLanguages")),
		connect.WithHandlerOptions(opts...),
	)
	clinksServiceSaveLanguageHandler := connect.NewUnaryHandler(
		ClinksServiceSaveLanguageProcedure,
		svc.SaveLanguage,
		connect.WithSchema(clinksServiceMethods.ByName("SaveLanguage")),
		connect.WithHandlerOptions(opts...),
	)
	clinksServiceSaveTranslationHandler := connect.NewUnaryHandler(
		ClinksServiceSaveTranslationProcedure,
		svc.SaveTranslation,
		connect.WithSchema(clinksServiceMethods.ByName("SaveTranslation")),
		connect.WithHandlerOptions(opts...),
	)
	clinksServiceListAuditEventsHandler := connect.NewUnaryHandler(
		ClinksServiceListAuditEventsProcedure,
		svc.ListAuditEvents,
		connect.WithSchema(clinksServiceMethods.ByName("ListAuditEvents")),
		connect.WithHandlerOptions(opts...),
	)
	clinksServiceListUsersHandler := connect.NewUnaryHandler(
		ClinksServiceListUsersProcedure,
		svc.ListUsers,
		connect.WithSchema(clinksServiceMethods.ByName("ListUsers")),
		connect.WithHandlerOptions(opts...),
	)
	clinksServiceGetUserHandler := connect.NewUnaryHandler(
		ClinksServiceGetUserProcedure,
		svc.GetUser,
		connect.WithSchema(clinksServiceMethods.ByName("GetUser")),
		connect.WithHandlerOptions(opts...),
	)
	clinksServiceListInvitationsHandler := connect.NewUnaryHandler(
		ClinksServiceListInvitationsProcedure,
		svc.ListInvitations,
		connect.WithSchema(clinksServiceMethods.ByName("ListInvitations")),
		connect.WithHandlerOptions(opts...),
	)
	clinksServiceRevokeInvitationHandler := connect.NewUnaryHandler(
		ClinksServiceRevokeInvitationProcedure,
		svc.RevokeInvitation,
		connect.WithSchema(clinksServiceMethods.ByName("RevokeInvitation")),
		connect.WithHandlerOptions(opts...),
	)
	clinksServiceGetSystemStatsHandler := connect.NewUnaryHandler(
		ClinksServiceGetSystemStatsProcedure,
		svc.GetSystemStats,
		connect.WithSchema(clinksServiceMethods.ByName("GetSystemStats")),
		connect.WithHandlerOptions(opts...),
	)
	return "/clinks.v1.ClinksService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ClinksServiceLoginProcedure:
			clinksServiceLoginHandler.ServeHTTP(w, r)
		case ClinksServiceLoginSuperAdminProcedure:
			clinksServiceLoginSuperAdminHandler.ServeHTTP(w, r)
		case ClinksServiceRegisterProcedure:
			clinksServiceRegisterHandler.ServeHTTP(w, r)
		case ClinksServiceLogoutProcedure:
			clinksServiceLogoutHandler.ServeHTTP(w, r)
		case ClinksServiceGetSessionProcedure:
			clinksServiceGetSessionHandler.ServeHTTP(w, r)
		case ClinksServiceSwitchTenantProcedure:
			clinksServiceSwitchTenantHandler.ServeHTTP(w, r)
		case ClinksServiceCreateInvitationProcedure:
			clinksServiceCreateInvitationHandler.ServeHTTP(w, r)
		case ClinksServiceAcceptInvitationProcedure:
			clinksServiceAcceptInvitationHandler.ServeHTTP(w, r)
		case ClinksServiceGetLanguagesProcedure:
			clinksServiceGetLanguagesHandler.ServeHTTP(w, r)
		case ClinksServiceGetTranslationsProcedure:
			clinksServiceGetTranslationsHandler.ServeHTTP(w, r)
		case ClinksServiceListTenantsProcedure:
			clinksServiceListTenantsHandler.ServeHTTP(w, r)
		case ClinksServiceCreateTenantProcedure:
			clinksServiceCreateTenantHandler.ServeHTTP(w, r)
		case ClinksServiceListManagedLanguagesProcedure:
			clinksServiceListManagedLanguagesHandler.ServeHTTP(w, r)
		case ClinksServiceSaveLanguageProcedure:
			clinksServiceSaveLanguageHandler.ServeHTTP(w, r)
		case ClinksServiceSaveTranslationProcedure:
			clinksServiceSaveTranslationHandler.ServeHTTP(w, r)
		case ClinksServiceListAuditEventsProcedure:
			clinksServiceListAuditEventsHandler.ServeHTTP(w, r)
		case ClinksServiceListUsersProcedure:
			clinksServiceListUsersHandler.ServeHTTP(w, r)
		case ClinksServiceGetUserProcedure:
			clinksServiceGetUserHandler.ServeHTTP(w, r)
		case ClinksServiceListInvitationsProcedure:
			clinksServiceListInvitationsHandler.ServeHTTP(w, r)
		case ClinksServiceRevokeInvitationProcedure:
			clinksServiceRevokeInvitationHandler.ServeHTTP(w, r)
		case ClinksServiceGetSystemStatsProcedure:
			clinksServiceGetSystemStatsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedClinksServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedClinksServiceHandler struct{}

func (UnimplementedClinksServiceHandler) Login(context.Context, *connect.Request[v1.CredentialsRequest]) (*connect.Response[v1.Session], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("clinks.v1.ClinksService.Login is not implemented"))
}

func (UnimplementedClinksServiceHandler) LoginSuperAdmin(context.Context, *connect.Request[v1.CredentialsRequest]) (*connect.Response[v1.Session], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("clinks.v1.ClinksService.LoginSuperAdmin is not implemented"))
}

func (UnimplementedClinksServiceHandler) Register(context.Context, *connect.Request[v1.RegisterRequest]) (*connect.Response[v1.Session], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("clinks.v1.ClinksService.Register is not implemented"))
}

func (UnimplementedClinksServiceHandler) Logout(context.Context, *connect.Request[v1.Empty]) (*connect.Response[v1.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("clinks.v1.ClinksService.Logout is not implemented"))
}

func (UnimplementedClinksServiceHandler) GetSession(context.Context, *connect.Request[v1.Empty]) (*connect.Response[v1.Session], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("clinks.v1.ClinksService.GetSession is not implemented"))
}

func (UnimplementedClinksServiceHandler) SwitchTenant(context.Context, *connect.Request[v1.SwitchTenantRequest]) (*connect.Response[v1.Session], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("clinks.v1.ClinksService.SwitchTenant is not implemented"))
}

func (UnimplementedClinksServiceHandler) CreateInvitation(context.Context, *connect.Request[v1.CreateInvitationRequest]) (*connect.Response[v1.Invitation], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("clinks.v1.ClinksService.CreateInvitation is not implemented"))
}

func (UnimplementedClinksServiceHandler) AcceptInvitation(context.Context, *connect.Request[v1.AcceptInvitationRequest]) (*connect.Response[v1.Session], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("clinks.v1.ClinksService.AcceptInvitation is not implemented"))
}

func (UnimplementedClinksServiceHandler) GetLanguages(context.Context, *connect.Request[v1.Empty]) (*connect.Response[v1.LanguagesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("clinks.v1.ClinksService.GetLanguages is not implemented"))
}

func (UnimplementedClinksServiceHandler) GetTranslations(context.Context, *connect.Request[v1.GetTranslationsRequest]) (*connect.Response[v1.TranslationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("clinks.v1.ClinksService.GetTranslations is not implemented"))
}

func (UnimplementedClinksServiceHandler) ListTenants(context.Context, *connect.Request[v1.Empty]) (*connect.Response[v1.TenantsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("clinks.v1.ClinksService.ListTenants is not implemented"))
}

func (UnimplementedClinksServiceHandler) CreateTenant(context.Context, *connect.Request[v1.CreateTenantRequest]) (*connect.Response[v1.Tenant], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("clinks.v1.ClinksService.CreateTenant is not implemented"))
}

func (UnimplementedClinksServiceHandler) ListManagedLanguages(context.Context, *connect.Request[v1.Empty]) (*connect.Response[v1.LanguagesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("clinks.v1.ClinksService.ListManagedLanguages is not implemented"))
}

func (UnimplementedClinksServiceHandler) SaveLanguage(context.Context, *connect.Request[v1.Language]) (*connect.Response[v1.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("clinks.v1.ClinksService.SaveLanguage is not implemented"))
}

func (UnimplementedClinksServiceHandler) SaveTranslation(context.Context, *connect.Request[v1.ScopedTranslation]) (*connect.Response[v1.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("clinks.v1.ClinksService.SaveTranslation is not implemented"))
}

func (UnimplementedClinksServiceHandler) ListAuditEvents(context.Context, *connect.Request[v1.ListAuditEventsRequest]) (*connect.Response[v1.AuditEventsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("clinks.v1.ClinksService.ListAuditEvents is not implemented"))
}

func (UnimplementedClinksServiceHandler) ListUsers(context.Context, *connect.Request[v1.ListUsersRequest]) (*connect.Response[v1.ListUsersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("clinks.v1.ClinksService.ListUsers is not implemented"))
}

func (UnimplementedClinksServiceHandler) GetUser(context.Context, *connect.Request[v1.GetUserRequest]) (*connect.Response[v1.UserDetail], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("clinks.v1.ClinksService.GetUser is not implemented"))
}

func (UnimplementedClinksServiceHandler) ListInvitations(context.Context, *connect.Request[v1.ListInvitationsRequest]) (*connect.Response[v1.ListInvitationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("clinks.v1.ClinksService.ListInvitations is not implemented"))
}

func (UnimplementedClinksServiceHandler) RevokeInvitation(context.Context, *connect.Request[v1.RevokeInvitationRequest]) (*connect.Response[v1.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("clinks.v1.ClinksService.RevokeInvitation is not implemented"))
}

func (UnimplementedClinksServiceHandler) GetSystemStats(context.Context, *connect.Request[v1.Empty]) (*connect.Response[v1.SystemStats], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("clinks.v1.ClinksService.GetSystemStats is not implemented"))
}
