// Code generated from localization/product-catalog.json. DO NOT EDIT.

package localization

import "github.com/besartmorina/clinks/server/internal/core/domain"

const productDefaultLocale domain.Locale = "de-CH"

var productTranslationEntries = []domain.Translation{
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "audit.invitation.accepted", Value: "Einladung angenommen: {target}"},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "audit.invitation.accepted", Value: "Invitation accepted: {target}"},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "audit.invitation.created", Value: "Einladung erstellt: {target}"},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "audit.invitation.created", Value: "Invitation created: {target}"},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "audit.localization.language_saved", Value: "Sprache geändert: {target}"},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "audit.localization.language_saved", Value: "Language changed: {target}"},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "audit.localization.translation_override_saved", Value: "Übersetzungs-Override geändert: {target}"},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "audit.localization.translation_override_saved", Value: "Translation override changed: {target}"},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "audit.localization.translation_saved", Value: "Übersetzung geändert: {target}"},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "audit.localization.translation_saved", Value: "Translation changed: {target}"},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "audit.session.login", Value: "Anmeldung erfolgreich: {target}"},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "audit.session.login", Value: "Successful sign-in: {target}"},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "audit.session.logout", Value: "Abmeldung: {target}"},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "audit.session.logout", Value: "Sign-out: {target}"},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "audit.tenant.created", Value: "Mandant erstellt: {target}"},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "audit.tenant.created", Value: "Tenant created: {target}"},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "audit.tenant.registered", Value: "Mandant registriert: {target}"},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "audit.tenant.registered", Value: "Tenant registered: {target}"},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "audit.tenant.switch", Value: "Mandant gewechselt: {target}"},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "audit.tenant.switch", Value: "Tenant switched: {target}"},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "error.email_taken", Value: "Diese E-Mail-Adresse wird bereits verwendet."},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "error.email_taken", Value: "This email address is already in use."},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "error.internal", Value: "Ein interner Fehler ist aufgetreten. Bitte versuche es erneut."},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "error.internal", Value: "An internal error occurred. Please try again."},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "error.invalid_credentials", Value: "E-Mail oder Passwort ist ungültig."},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "error.invalid_credentials", Value: "Email or password is invalid."},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "error.invitation_expired", Value: "Die Einladung ist abgelaufen."},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "error.invitation_expired", Value: "The invitation has expired."},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "error.invitation_invalid", Value: "Die Einladung ist ungültig."},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "error.invitation_invalid", Value: "The invitation is invalid."},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "error.invitation_used", Value: "Die Einladung wurde bereits verwendet."},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "error.invitation_used", Value: "The invitation has already been used."},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "error.invite_email_mismatch", Value: "Diese Einladung gehört zu einer anderen E-Mail-Adresse."},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "error.invite_email_mismatch", Value: "This invitation belongs to a different email address."},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "error.membership_not_found", Value: "Die Mitgliedschaft wurde nicht gefunden."},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "error.membership_not_found", Value: "The membership was not found."},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "error.tenant_not_found", Value: "Der Mandant wurde nicht gefunden."},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "error.tenant_not_found", Value: "The tenant was not found."},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "error.unauthorized", Value: "Für diese Aktion fehlen die erforderlichen Rechte."},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "error.unauthorized", Value: "You do not have permission to perform this action."},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "error.validation", Value: "Bitte überprüfe die eingegebenen Daten."},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "error.validation", Value: "Please check the submitted values."},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "ui.action", Value: "Aktion"},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "ui.action", Value: "Action"},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "ui.active_tenant", Value: "Aktiver Mandant"},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "ui.active_tenant", Value: "Active tenant"},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "ui.actor_id", Value: "Benutzer-ID"},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "ui.actor_id", Value: "User ID"},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "ui.add_translation", Value: "Override speichern"},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "ui.add_translation", Value: "Save override"},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "ui.admin_login", Value: "Admin-Anmeldung"},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "ui.admin_login", Value: "Administrator sign in"},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "ui.application_infra_link", Value: "Infrastruktur"},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "ui.application_infra_link", Value: "Infrastructure"},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "ui.application_planer_link", Value: "Planung"},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "ui.application_planer_link", Value: "Planning"},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "ui.audit_default_range", Value: "Standard: letzte 30 Tage."},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "ui.audit_default_range", Value: "Default: last 30 days."},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "ui.audit_description", Value: "Beschreibung"},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "ui.audit_description", Value: "Description"},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "ui.audit_immutable", Value: "Ereignisse sind unveränderbar."},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "ui.audit_immutable", Value: "Events cannot be changed."},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "ui.audit_log", Value: "Audit-Protokoll"},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "ui.audit_log", Value: "Audit log"},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "ui.back_to_home", Value: "Zurück zur Startseite"},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "ui.back_to_home", Value: "Back to Home"},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "ui.connected_to_tenant", Value: "ist mit dem Mandanten verbunden."},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "ui.connected_to_tenant", Value: "is connected to the tenant."},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "ui.copy", Value: "Kopieren"},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "ui.copy", Value: "Copy"},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "ui.create_tenant", Value: "Mandant erstellen"},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "ui.create_tenant", Value: "Create tenant"},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "ui.dashboard", Value: "Dashboard"},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "ui.dashboard", Value: "Dashboard"},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "ui.default", Value: "Standard"},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "ui.default", Value: "Default"},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "ui.email", Value: "E-Mail-Adresse"},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "ui.email", Value: "Email address"},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "ui.error_forbidden_desc", Value: "Du verfügst nicht über die erforderlichen Rechte für diesen Bereich."},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "ui.error_forbidden_desc", Value: "You do not have permission to access this area."},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "ui.error_forbidden_title", Value: "Zugriff verweigert"},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "ui.error_forbidden_title", Value: "Access denied"},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "ui.error_generic_desc", Value: "Ein unerwarteter Fehler ist aufgetreten. Bitte versuche es erneut."},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "ui.error_generic_desc", Value: "An unexpected error occurred. Please try again."},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "ui.error_generic_title", Value: "Unerwarteter Fehler"},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "ui.error_generic_title", Value: "Unexpected error"},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "ui.error_not_found_desc", Value: "Die angeforderte Seite existiert nicht oder wurde verschoben."},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "ui.error_not_found_desc", Value: "The requested page does not exist or has been moved."},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "ui.error_not_found_title", Value: "Seite nicht gefunden"},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "ui.error_not_found_title", Value: "Page not found"},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "ui.error_server_desc", Value: "Beim Verarbeiten der Anfrage ist ein interner Serverfehler aufgetreten."},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "ui.error_server_desc", Value: "An internal server error occurred while processing the request."},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "ui.error_server_title", Value: "Serverfehler"},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "ui.error_server_title", Value: "Server error"},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "ui.filter", Value: "Filtern"},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "ui.filter", Value: "Filter"},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "ui.from", Value: "Von"},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "ui.from", Value: "From"},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "ui.invitation_link", Value: "Einladungslink"},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "ui.invitation_link", Value: "Invitation link"},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "ui.invite_user", Value: "Benutzer einladen"},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "ui.invite_user", Value: "Invite user"},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "ui.languages", Value: "Sprachen"},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "ui.languages", Value: "Languages"},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "ui.load_more", Value: "Mehr laden"},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "ui.load_more", Value: "Load more"},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "ui.loading", Value: "Wird geladen …"},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "ui.loading", Value: "Loading …"},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "ui.locale", Value: "Gebietsschema"},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "ui.locale", Value: "Locale"},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "ui.no_tenants", Value: "Noch keine Mandanten vorhanden."},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "ui.no_tenants", Value: "No tenants yet."},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "ui.occurred_at", Value: "Zeitpunkt"},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "ui.occurred_at", Value: "Occurred at"},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "ui.password", Value: "Passwort"},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "ui.password", Value: "Password"},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "ui.register", Value: "Registrieren"},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "ui.register", Value: "Register"},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "ui.role", Value: "Rolle"},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "ui.role", Value: "Role"},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "ui.role_tenant_admin", Value: "Mandantenadministrator"},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "ui.role_tenant_admin", Value: "Tenant administrator"},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "ui.role_user", Value: "Benutzer"},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "ui.role_user", Value: "User"},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "ui.save", Value: "Speichern"},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "ui.save", Value: "Save"},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "ui.scope_admin", Value: "Administration"},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "ui.scope_admin", Value: "Administration"},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "ui.scope_infra_link", Value: "Infrastruktur"},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "ui.scope_infra_link", Value: "Infrastructure"},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "ui.scope_planer_link", Value: "Planung"},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "ui.scope_planer_link", Value: "Planning"},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "ui.scope_shared", Value: "Übergreifend"},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "ui.scope_shared", Value: "Shared"},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "ui.sign_in", Value: "Anmelden"},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "ui.sign_in", Value: "Sign in"},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "ui.sign_out", Value: "Abmelden"},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "ui.sign_out", Value: "Sign out"},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "ui.status_code", Value: "Status {code}"},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "ui.status_code", Value: "Status {code}"},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "ui.super_administrator", Value: "Super-Administrator"},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "ui.super_administrator", Value: "Super administrator"},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "ui.tenant_id", Value: "Mandanten-ID"},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "ui.tenant_id", Value: "Tenant ID"},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "ui.tenant_name", Value: "Mandantenname"},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "ui.tenant_name", Value: "Tenant name"},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "ui.tenants", Value: "Mandanten"},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "ui.tenants", Value: "Tenants"},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "ui.theme", Value: "Darstellung"},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "ui.theme", Value: "Theme"},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "ui.theme_dark", Value: "Dunkel"},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "ui.theme_dark", Value: "Dark"},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "ui.theme_light", Value: "Hell"},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "ui.theme_light", Value: "Light"},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "ui.theme_system", Value: "System"},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "ui.theme_system", Value: "System"},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "ui.to", Value: "Bis"},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "ui.to", Value: "To"},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "ui.translation_key", Value: "Übersetzungsschlüssel"},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "ui.translation_key", Value: "Translation key"},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "ui.translation_scope", Value: "Bereich"},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "ui.translation_scope", Value: "Scope"},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "ui.translation_value", Value: "Override-Text"},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "ui.translation_value", Value: "Override text"},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "ui.translations", Value: "Übersetzungs-Overrides"},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "ui.translations", Value: "Translation overrides"},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "ui.try_again", Value: "Erneut versuchen"},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "ui.try_again", Value: "Try Again"},
	{Locale: "de-CH", ApplicationScope: domain.ScopeShared, Key: "ui.welcome", Value: "Willkommen"},
	{Locale: "en-US", ApplicationScope: domain.ScopeShared, Key: "ui.welcome", Value: "Welcome"},
}
