// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/besartmorina/clinks/server/internal/adapters/auth"
	"github.com/besartmorina/clinks/server/internal/adapters/mail"
	"github.com/besartmorina/clinks/server/internal/adapters/postgres"
	"github.com/besartmorina/clinks/server/internal/config"
	"github.com/besartmorina/clinks/server/internal/core/ports"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeWorker(ctx context.Context, cfg *config.Config) (*WorkerApplication, func(), error) {
	poolConfig := workerPoolConfig(cfg)
	pool, cleanup, err := postgres.NewPool(ctx, poolConfig)
	if err != nil {
		return nil, nil, err
	}
	outboxRepository := postgres.NewOutboxRepository(pool)
	smtpConfig := workerSMTPConfig(cfg)
	smtpMailer := mail.NewSMTPMailer(smtpConfig)
	invitationTokenConfig := workerInvitationTokenConfig(cfg)
	invitationTokenSigner, err := auth.NewInvitationTokenSigner(invitationTokenConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	string2 := workerInviteBaseURL(cfg)
	invitationWorker := newInvitationWorker(outboxRepository, smtpMailer, invitationTokenSigner, string2)
	workerApplication := NewWorkerApplication(pool, invitationWorker)
	return workerApplication, func() {
		cleanup()
	}, nil
}

// wire.go:

var configSet = wire.NewSet(
	workerPoolConfig,
	workerSMTPConfig,
	workerInvitationTokenConfig,
	workerInviteBaseURL,
)

var postgresSet = wire.NewSet(postgres.NewPool, postgres.NewOutboxRepository, wire.Bind(new(ports.OutboxRepository), new(*postgres.OutboxRepository)))

var mailSet = wire.NewSet(mail.NewSMTPMailer, wire.Bind(new(ports.InvitationMailer), new(*mail.SMTPMailer)))

var authSet = wire.NewSet(auth.NewInvitationTokenSigner, wire.Bind(new(ports.InvitationTokenSigner), new(*auth.InvitationTokenSigner)))

var workerSet = wire.NewSet(
	newInvitationWorker,
	NewWorkerApplication,
)

var workerProviderSet = wire.NewSet(
	configSet,
	postgresSet,
	mailSet,
	authSet,
	workerSet,
)
