// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/besartmorina/clinks/server/internal/adapters/auth"
	"github.com/besartmorina/clinks/server/internal/adapters/mail"
	"github.com/besartmorina/clinks/server/internal/adapters/postgres"
	"github.com/besartmorina/clinks/server/internal/config"
	"github.com/besartmorina/clinks/server/internal/core/ports"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeWorker(contextContext context.Context, configConfig *config.Config) (*WorkerApplication, error) {
	poolConfig := workerPoolConfig(configConfig)
	pool, err := postgres.NewPool(contextContext, poolConfig)
	if err != nil {
		return nil, err
	}
	outboxRepository := postgres.NewOutboxRepository(pool)
	smtpConfig := workerSmtpConfig(configConfig)
	smtpMailer := mail.NewSMTPMailer(smtpConfig)
	invitationTokenConfig := workerInvitationTokenConfig(configConfig)
	invitationTokenSigner, err := auth.NewInvitationTokenSigner(invitationTokenConfig)
	if err != nil {
		return nil, err
	}
	string2 := workerInviteBaseURL(configConfig)
	invitationWorker := newInvitationWorker(outboxRepository, smtpMailer, invitationTokenSigner, string2)
	workerApplication := NewWorkerApplication(pool, invitationWorker)
	return workerApplication, nil
}

// wire.go:

var workerProviderSet = wire.NewSet(
	workerPoolConfig,
	workerSmtpConfig,
	workerInvitationTokenConfig,
	workerInviteBaseURL, postgres.NewPool, postgres.NewOutboxRepository, mail.NewSMTPMailer, auth.NewInvitationTokenSigner, wire.Bind(new(ports.OutboxRepository), new(*postgres.OutboxRepository)), wire.Bind(new(ports.InvitationMailer), new(*mail.SMTPMailer)), wire.Bind(new(ports.InvitationTokenSigner), new(*auth.InvitationTokenSigner)), newInvitationWorker,
	NewWorkerApplication,
)
