// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/besartmorina/clinks/server/internal/adapters/auth"
	"github.com/besartmorina/clinks/server/internal/adapters/i18n"
	"github.com/besartmorina/clinks/server/internal/adapters/localization"
	"github.com/besartmorina/clinks/server/internal/adapters/mail"
	"github.com/besartmorina/clinks/server/internal/adapters/postgres"
	"github.com/besartmorina/clinks/server/internal/adapters/security"
	"github.com/besartmorina/clinks/server/internal/config"
	"github.com/besartmorina/clinks/server/internal/core/ports"
	"github.com/besartmorina/clinks/server/internal/core/service"
	"github.com/google/wire"
)

// Injectors from wire.go:

// InitializeApplication generates the dependency injection graph via Google Wire.
func InitializeApplication(ctx context.Context, cfg *config.Config) (*Application, func(), error) {
	postgresPoolConfig := poolConfig(cfg)
	pool, cleanup, err := postgres.NewPool(ctx, postgresPoolConfig)
	if err != nil {
		return nil, nil, err
	}
	userRepository := postgres.NewUserRepository(pool)
	externalIdentityRepository := postgres.NewExternalIdentityRepository(pool)
	tenantProvisioner := postgres.NewTenantProvisioner(pool)
	membershipRepository := postgres.NewMembershipRepository(pool)
	passwordHasher := security.NewPasswordHasher()
	authSessionConfig := sessionConfig(cfg)
	sessionIssuer, err := auth.NewSessionIssuer(authSessionConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	auditRepository := postgres.NewAuditRepository(pool)
	authInvitationTokenConfig := invitationTokenConfig(cfg)
	invitationTokenSigner, err := auth.NewInvitationTokenSigner(authInvitationTokenConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	string2 := inviteBaseURL(cfg)
	duration := inviteTTL(cfg)
	authService := newAuthService(userRepository, externalIdentityRepository, tenantProvisioner, membershipRepository, passwordHasher, sessionIssuer, auditRepository, invitationTokenSigner, string2, duration)
	tenantRepository := postgres.NewTenantRepository(pool)
	localizationRepository := postgres.NewLocalizationRepository(pool)
	productCatalog := localization.NewProductCatalog(localizationRepository)
	adminUserRepository := postgres.NewAdminUserRepository(pool)
	adminInvitationRepository := postgres.NewAdminInvitationRepository(pool)
	systemStatsRepository := postgres.NewSystemStatsRepository(pool)
	adminService := service.NewAdminService(tenantRepository, productCatalog, localizationRepository, auditRepository, adminUserRepository, adminInvitationRepository, systemStatsRepository)
	i18nService := service.NewI18nService(productCatalog)
	translator := i18n.NewTranslator(productCatalog)
	readiness := postgres.NewReadiness(pool)
	serverConfig := httpServerConfig(cfg)
	server := newHTTPServer(authService, adminService, i18nService, translator, readiness, serverConfig)
	authGoogleOIDCConfig := googleOIDCConfig(cfg)
	googleOIDC := auth.NewGoogleOIDC(authGoogleOIDCConfig)
	oidcConfig := httpOIDCConfig(cfg)
	application := NewApplication(server, pool, authService, googleOIDC, oidcConfig)
	return application, func() {
		cleanup()
	}, nil
}

// wire.go:

var configSet = wire.NewSet(
	poolConfig,
	httpServerConfig,
	sessionConfig,
	smtpConfig,
	invitationTokenConfig,
	googleOIDCConfig,
	httpOIDCConfig,
	inviteBaseURL,
	inviteTTL,
)

var postgresSet = wire.NewSet(postgres.NewPool, postgres.NewUserRepository, wire.Bind(new(ports.IdentityRepository), new(*postgres.UserRepository)), postgres.NewExternalIdentityRepository, wire.Bind(new(ports.ExternalIdentityRepository), new(*postgres.ExternalIdentityRepository)), postgres.NewTenantProvisioner, wire.Bind(new(ports.TenantProvisioner), new(*postgres.TenantProvisioner)), postgres.NewTenantRepository, wire.Bind(new(ports.TenantRepository), new(*postgres.TenantRepository)), postgres.NewMembershipRepository, wire.Bind(new(ports.MembershipRepository), new(*postgres.MembershipRepository)), postgres.NewAuditRepository, wire.Bind(new(ports.AuditLog), new(*postgres.AuditRepository)), postgres.NewLocalizationRepository, wire.Bind(new(ports.LocalizationOverrides), new(*postgres.LocalizationRepository)), wire.Bind(new(ports.LocalizationEditor), new(*postgres.LocalizationRepository)), postgres.NewAdminUserRepository, wire.Bind(new(ports.AdminUserRepository), new(*postgres.AdminUserRepository)), postgres.NewAdminInvitationRepository, wire.Bind(new(ports.AdminInvitationRepository), new(*postgres.AdminInvitationRepository)), postgres.NewSystemStatsRepository, wire.Bind(new(ports.SystemStatsRepository), new(*postgres.SystemStatsRepository)), postgres.NewReadiness, wire.Bind(new(ports.ReadinessChecker), new(*postgres.Readiness)))

var securitySet = wire.NewSet(security.NewPasswordHasher, wire.Bind(new(ports.PasswordHasher), new(*security.PasswordHasher)))

var authSet = wire.NewSet(auth.NewSessionIssuer, wire.Bind(new(ports.SessionIssuer), new(*auth.SessionIssuer)), auth.NewInvitationTokenSigner, wire.Bind(new(ports.InvitationTokenSigner), new(*auth.InvitationTokenSigner)), auth.NewGoogleOIDC)

var mailSet = wire.NewSet(mail.NewSMTPMailer, wire.Bind(new(ports.InvitationMailer), new(*mail.SMTPMailer)))

var localizationSet = wire.NewSet(localization.NewProductCatalog, wire.Bind(new(ports.LocalizationCatalog), new(*localization.ProductCatalog)), i18n.NewTranslator)

var serviceSet = wire.NewSet(
	newAuthService, service.NewAdminService, service.NewI18nService,
)

var httpSet = wire.NewSet(
	newHTTPServer,
	NewApplication,
)

var providerSet = wire.NewSet(
	configSet,
	postgresSet,
	securitySet,
	authSet,
	mailSet,
	localizationSet,
	serviceSet,
	httpSet,
)
