// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: clinks/v1/clinks.proto

package clinksv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_clinks_v1_clinks_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_clinks_v1_clinks_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_clinks_v1_clinks_proto_rawDescGZIP(), []int{0}
}

type CredentialsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialsRequest) Reset() {
	*x = CredentialsRequest{}
	mi := &file_clinks_v1_clinks_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialsRequest) ProtoMessage() {}

func (x *CredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clinks_v1_clinks_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialsRequest.ProtoReflect.Descriptor instead.
func (*CredentialsRequest) Descriptor() ([]byte, []int) {
	return file_clinks_v1_clinks_proto_rawDescGZIP(), []int{1}
}

func (x *CredentialsRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CredentialsRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	TenantName    string                 `protobuf:"bytes,3,opt,name=tenant_name,json=tenantName,proto3" json:"tenant_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_clinks_v1_clinks_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clinks_v1_clinks_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_clinks_v1_clinks_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetTenantName() string {
	if x != nil {
		return x.TenantName
	}
	return ""
}

type SwitchTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwitchTenantRequest) Reset() {
	*x = SwitchTenantRequest{}
	mi := &file_clinks_v1_clinks_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchTenantRequest) ProtoMessage() {}

func (x *SwitchTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clinks_v1_clinks_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchTenantRequest.ProtoReflect.Descriptor instead.
func (*SwitchTenantRequest) Descriptor() ([]byte, []int) {
	return file_clinks_v1_clinks_proto_rawDescGZIP(), []int{3}
}

func (x *SwitchTenantRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Locale        string                 `protobuf:"bytes,3,opt,name=locale,proto3" json:"locale,omitempty"`
	IsSuperAdmin  bool                   `protobuf:"varint,4,opt,name=is_super_admin,json=isSuperAdmin,proto3" json:"is_super_admin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_clinks_v1_clinks_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_clinks_v1_clinks_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_clinks_v1_clinks_proto_rawDescGZIP(), []int{4}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *User) GetIsSuperAdmin() bool {
	if x != nil {
		return x.IsSuperAdmin
	}
	return false
}

type Tenant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tenant) Reset() {
	*x = Tenant{}
	mi := &file_clinks_v1_clinks_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tenant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tenant) ProtoMessage() {}

func (x *Tenant) ProtoReflect() protoreflect.Message {
	mi := &file_clinks_v1_clinks_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tenant.ProtoReflect.Descriptor instead.
func (*Tenant) Descriptor() ([]byte, []int) {
	return file_clinks_v1_clinks_proto_rawDescGZIP(), []int{5}
}

func (x *Tenant) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tenant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Membership struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Tenant        *Tenant                `protobuf:"bytes,2,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Membership) Reset() {
	*x = Membership{}
	mi := &file_clinks_v1_clinks_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Membership) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Membership) ProtoMessage() {}

func (x *Membership) ProtoReflect() protoreflect.Message {
	mi := &file_clinks_v1_clinks_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Membership.ProtoReflect.Descriptor instead.
func (*Membership) Descriptor() ([]byte, []int) {
	return file_clinks_v1_clinks_proto_rawDescGZIP(), []int{6}
}

func (x *Membership) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Membership) GetTenant() *Tenant {
	if x != nil {
		return x.Tenant
	}
	return nil
}

func (x *Membership) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Membership) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	ActiveTenant  *Tenant                `protobuf:"bytes,2,opt,name=active_tenant,json=activeTenant,proto3" json:"active_tenant,omitempty"`
	Memberships   []*Membership          `protobuf:"bytes,3,rep,name=memberships,proto3" json:"memberships,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_clinks_v1_clinks_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_clinks_v1_clinks_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_clinks_v1_clinks_proto_rawDescGZIP(), []int{7}
}

func (x *Session) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *Session) GetActiveTenant() *Tenant {
	if x != nil {
		return x.ActiveTenant
	}
	return nil
}

func (x *Session) GetMemberships() []*Membership {
	if x != nil {
		return x.Memberships
	}
	return nil
}

type CreateInvitationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInvitationRequest) Reset() {
	*x = CreateInvitationRequest{}
	mi := &file_clinks_v1_clinks_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInvitationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInvitationRequest) ProtoMessage() {}

func (x *CreateInvitationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clinks_v1_clinks_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInvitationRequest.ProtoReflect.Descriptor instead.
func (*CreateInvitationRequest) Descriptor() ([]byte, []int) {
	return file_clinks_v1_clinks_proto_rawDescGZIP(), []int{8}
}

func (x *CreateInvitationRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateInvitationRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type Invitation struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId       string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Email          string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Role           string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	ExpiresAt      string                 `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	AcceptanceUrl  string                 `protobuf:"bytes,6,opt,name=acceptance_url,json=acceptanceUrl,proto3" json:"acceptance_url,omitempty"`
	DeliveryStatus string                 `protobuf:"bytes,7,opt,name=delivery_status,json=deliveryStatus,proto3" json:"delivery_status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Invitation) Reset() {
	*x = Invitation{}
	mi := &file_clinks_v1_clinks_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Invitation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Invitation) ProtoMessage() {}

func (x *Invitation) ProtoReflect() protoreflect.Message {
	mi := &file_clinks_v1_clinks_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Invitation.ProtoReflect.Descriptor instead.
func (*Invitation) Descriptor() ([]byte, []int) {
	return file_clinks_v1_clinks_proto_rawDescGZIP(), []int{9}
}

func (x *Invitation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Invitation) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Invitation) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Invitation) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Invitation) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *Invitation) GetAcceptanceUrl() string {
	if x != nil {
		return x.AcceptanceUrl
	}
	return ""
}

func (x *Invitation) GetDeliveryStatus() string {
	if x != nil {
		return x.DeliveryStatus
	}
	return ""
}

type AcceptInvitationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptInvitationRequest) Reset() {
	*x = AcceptInvitationRequest{}
	mi := &file_clinks_v1_clinks_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptInvitationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptInvitationRequest) ProtoMessage() {}

func (x *AcceptInvitationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clinks_v1_clinks_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptInvitationRequest.ProtoReflect.Descriptor instead.
func (*AcceptInvitationRequest) Descriptor() ([]byte, []int) {
	return file_clinks_v1_clinks_proto_rawDescGZIP(), []int{10}
}

func (x *AcceptInvitationRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AcceptInvitationRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AcceptInvitationRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type Language struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IsDefault     bool                   `protobuf:"varint,3,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	IsActive      bool                   `protobuf:"varint,4,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Language) Reset() {
	*x = Language{}
	mi := &file_clinks_v1_clinks_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Language) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Language) ProtoMessage() {}

func (x *Language) ProtoReflect() protoreflect.Message {
	mi := &file_clinks_v1_clinks_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Language.ProtoReflect.Descriptor instead.
func (*Language) Descriptor() ([]byte, []int) {
	return file_clinks_v1_clinks_proto_rawDescGZIP(), []int{11}
}

func (x *Language) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Language) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Language) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

func (x *Language) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type LanguagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Languages     []*Language            `protobuf:"bytes,1,rep,name=languages,proto3" json:"languages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LanguagesResponse) Reset() {
	*x = LanguagesResponse{}
	mi := &file_clinks_v1_clinks_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LanguagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LanguagesResponse) ProtoMessage() {}

func (x *LanguagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clinks_v1_clinks_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LanguagesResponse.ProtoReflect.Descriptor instead.
func (*LanguagesResponse) Descriptor() ([]byte, []int) {
	return file_clinks_v1_clinks_proto_rawDescGZIP(), []int{12}
}

func (x *LanguagesResponse) GetLanguages() []*Language {
	if x != nil {
		return x.Languages
	}
	return nil
}

type GetTranslationsRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ApplicationScope string                 `protobuf:"bytes,1,opt,name=application_scope,json=applicationScope,proto3" json:"application_scope,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetTranslationsRequest) Reset() {
	*x = GetTranslationsRequest{}
	mi := &file_clinks_v1_clinks_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTranslationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTranslationsRequest) ProtoMessage() {}

func (x *GetTranslationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clinks_v1_clinks_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTranslationsRequest.ProtoReflect.Descriptor instead.
func (*GetTranslationsRequest) Descriptor() ([]byte, []int) {
	return file_clinks_v1_clinks_proto_rawDescGZIP(), []int{13}
}

func (x *GetTranslationsRequest) GetApplicationScope() string {
	if x != nil {
		return x.ApplicationScope
	}
	return ""
}

type ScopedTranslation struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Locale           string                 `protobuf:"bytes,1,opt,name=locale,proto3" json:"locale,omitempty"`
	ApplicationScope string                 `protobuf:"bytes,2,opt,name=application_scope,json=applicationScope,proto3" json:"application_scope,omitempty"`
	Key              string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Value            string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ScopedTranslation) Reset() {
	*x = ScopedTranslation{}
	mi := &file_clinks_v1_clinks_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScopedTranslation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScopedTranslation) ProtoMessage() {}

func (x *ScopedTranslation) ProtoReflect() protoreflect.Message {
	mi := &file_clinks_v1_clinks_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScopedTranslation.ProtoReflect.Descriptor instead.
func (*ScopedTranslation) Descriptor() ([]byte, []int) {
	return file_clinks_v1_clinks_proto_rawDescGZIP(), []int{14}
}

func (x *ScopedTranslation) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *ScopedTranslation) GetApplicationScope() string {
	if x != nil {
		return x.ApplicationScope
	}
	return ""
}

func (x *ScopedTranslation) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ScopedTranslation) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type TranslationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Locale        string                 `protobuf:"bytes,1,opt,name=locale,proto3" json:"locale,omitempty"`
	Translations  []*ScopedTranslation   `protobuf:"bytes,2,rep,name=translations,proto3" json:"translations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranslationsResponse) Reset() {
	*x = TranslationsResponse{}
	mi := &file_clinks_v1_clinks_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslationsResponse) ProtoMessage() {}

func (x *TranslationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clinks_v1_clinks_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslationsResponse.ProtoReflect.Descriptor instead.
func (*TranslationsResponse) Descriptor() ([]byte, []int) {
	return file_clinks_v1_clinks_proto_rawDescGZIP(), []int{15}
}

func (x *TranslationsResponse) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *TranslationsResponse) GetTranslations() []*ScopedTranslation {
	if x != nil {
		return x.Translations
	}
	return nil
}

type TenantsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenants       []*Tenant              `protobuf:"bytes,1,rep,name=tenants,proto3" json:"tenants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantsResponse) Reset() {
	*x = TenantsResponse{}
	mi := &file_clinks_v1_clinks_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantsResponse) ProtoMessage() {}

func (x *TenantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clinks_v1_clinks_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantsResponse.ProtoReflect.Descriptor instead.
func (*TenantsResponse) Descriptor() ([]byte, []int) {
	return file_clinks_v1_clinks_proto_rawDescGZIP(), []int{16}
}

func (x *TenantsResponse) GetTenants() []*Tenant {
	if x != nil {
		return x.Tenants
	}
	return nil
}

type CreateTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTenantRequest) Reset() {
	*x = CreateTenantRequest{}
	mi := &file_clinks_v1_clinks_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTenantRequest) ProtoMessage() {}

func (x *CreateTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clinks_v1_clinks_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTenantRequest.ProtoReflect.Descriptor instead.
func (*CreateTenantRequest) Descriptor() ([]byte, []int) {
	return file_clinks_v1_clinks_proto_rawDescGZIP(), []int{17}
}

func (x *CreateTenantRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListAuditEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	ActorId       string                 `protobuf:"bytes,3,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,4,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Action        string                 `protobuf:"bytes,5,opt,name=action,proto3" json:"action,omitempty"`
	Cursor        string                 `protobuf:"bytes,6,opt,name=cursor,proto3" json:"cursor,omitempty"`
	PageSize      uint32                 `protobuf:"varint,7,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuditEventsRequest) Reset() {
	*x = ListAuditEventsRequest{}
	mi := &file_clinks_v1_clinks_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuditEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuditEventsRequest) ProtoMessage() {}

func (x *ListAuditEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clinks_v1_clinks_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuditEventsRequest.ProtoReflect.Descriptor instead.
func (*ListAuditEventsRequest) Descriptor() ([]byte, []int) {
	return file_clinks_v1_clinks_proto_rawDescGZIP(), []int{18}
}

func (x *ListAuditEventsRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *ListAuditEventsRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *ListAuditEventsRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *ListAuditEventsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListAuditEventsRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ListAuditEventsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ListAuditEventsRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type AuditEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OccurredAt    string                 `protobuf:"bytes,2,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	ActorId       string                 `protobuf:"bytes,3,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	ActorEmail    string                 `protobuf:"bytes,4,opt,name=actor_email,json=actorEmail,proto3" json:"actor_email,omitempty"`
	TenantId      string                 `protobuf:"bytes,5,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	TenantName    string                 `protobuf:"bytes,6,opt,name=tenant_name,json=tenantName,proto3" json:"tenant_name,omitempty"`
	Action        string                 `protobuf:"bytes,7,opt,name=action,proto3" json:"action,omitempty"`
	Target        string                 `protobuf:"bytes,8,opt,name=target,proto3" json:"target,omitempty"`
	Description   string                 `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditEvent) Reset() {
	*x = AuditEvent{}
	mi := &file_clinks_v1_clinks_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditEvent) ProtoMessage() {}

func (x *AuditEvent) ProtoReflect() protoreflect.Message {
	mi := &file_clinks_v1_clinks_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditEvent.ProtoReflect.Descriptor instead.
func (*AuditEvent) Descriptor() ([]byte, []int) {
	return file_clinks_v1_clinks_proto_rawDescGZIP(), []int{19}
}

func (x *AuditEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuditEvent) GetOccurredAt() string {
	if x != nil {
		return x.OccurredAt
	}
	return ""
}

func (x *AuditEvent) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *AuditEvent) GetActorEmail() string {
	if x != nil {
		return x.ActorEmail
	}
	return ""
}

func (x *AuditEvent) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *AuditEvent) GetTenantName() string {
	if x != nil {
		return x.TenantName
	}
	return ""
}

func (x *AuditEvent) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuditEvent) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *AuditEvent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type AuditEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*AuditEvent          `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditEventsResponse) Reset() {
	*x = AuditEventsResponse{}
	mi := &file_clinks_v1_clinks_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditEventsResponse) ProtoMessage() {}

func (x *AuditEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clinks_v1_clinks_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditEventsResponse.ProtoReflect.Descriptor instead.
func (*AuditEventsResponse) Descriptor() ([]byte, []int) {
	return file_clinks_v1_clinks_proto_rawDescGZIP(), []int{20}
}

func (x *AuditEventsResponse) GetEvents() []*AuditEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *AuditEventsResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

var File_clinks_v1_clinks_proto protoreflect.FileDescriptor

const file_clinks_v1_clinks_proto_rawDesc = "" +
	"\n" +
	"\x16clinks/v1/clinks.proto\x12\tclinks.v1\"\a\n" +
	"\x05Empty\"F\n" +
	"\x12CredentialsRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"d\n" +
	"\x0fRegisterRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1f\n" +
	"\vtenant_name\x18\x03 \x01(\tR\n" +
	"tenantName\"2\n" +
	"\x13SwitchTenantRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"j\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x16\n" +
	"\x06locale\x18\x03 \x01(\tR\x06locale\x12$\n" +
	"\x0eis_super_admin\x18\x04 \x01(\bR\fisSuperAdmin\",\n" +
	"\x06Tenant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"s\n" +
	"\n" +
	"Membership\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12)\n" +
	"\x06tenant\x18\x02 \x01(\v2\x11.clinks.v1.TenantR\x06tenant\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"\x9f\x01\n" +
	"\aSession\x12#\n" +
	"\x04user\x18\x01 \x01(\v2\x0f.clinks.v1.UserR\x04user\x126\n" +
	"\ractive_tenant\x18\x02 \x01(\v2\x11.clinks.v1.TenantR\factiveTenant\x127\n" +
	"\vmemberships\x18\x03 \x03(\v2\x15.clinks.v1.MembershipR\vmemberships\"C\n" +
	"\x17CreateInvitationRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\"\xd2\x01\n" +
	"\n" +
	"Invitation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\tR\texpiresAt\x12%\n" +
	"\x0eacceptance_url\x18\x06 \x01(\tR\racceptanceUrl\x12'\n" +
	"\x0fdelivery_status\x18\a \x01(\tR\x0edeliveryStatus\"a\n" +
	"\x17AcceptInvitationRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"n\n" +
	"\bLanguage\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"is_default\x18\x03 \x01(\bR\tisDefault\x12\x1b\n" +
	"\tis_active\x18\x04 \x01(\bR\bisActive\"F\n" +
	"\x11LanguagesResponse\x121\n" +
	"\tlanguages\x18\x01 \x03(\v2\x13.clinks.v1.LanguageR\tlanguages\"E\n" +
	"\x16GetTranslationsRequest\x12+\n" +
	"\x11application_scope\x18\x01 \x01(\tR\x10applicationScope\"\x80\x01\n" +
	"\x11ScopedTranslation\x12\x16\n" +
	"\x06locale\x18\x01 \x01(\tR\x06locale\x12+\n" +
	"\x11application_scope\x18\x02 \x01(\tR\x10applicationScope\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\"p\n" +
	"\x14TranslationsResponse\x12\x16\n" +
	"\x06locale\x18\x01 \x01(\tR\x06locale\x12@\n" +
	"\ftranslations\x18\x02 \x03(\v2\x1c.clinks.v1.ScopedTranslationR\ftranslations\">\n" +
	"\x0fTenantsResponse\x12+\n" +
	"\atenants\x18\x01 \x03(\v2\x11.clinks.v1.TenantR\atenants\")\n" +
	"\x13CreateTenantRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xc1\x01\n" +
	"\x16ListAuditEventsRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12\x19\n" +
	"\bactor_id\x18\x03 \x01(\tR\aactorId\x12\x1b\n" +
	"\ttenant_id\x18\x04 \x01(\tR\btenantId\x12\x16\n" +
	"\x06action\x18\x05 \x01(\tR\x06action\x12\x16\n" +
	"\x06cursor\x18\x06 \x01(\tR\x06cursor\x12\x1b\n" +
	"\tpage_size\x18\a \x01(\rR\bpageSize\"\x89\x02\n" +
	"\n" +
	"AuditEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\voccurred_at\x18\x02 \x01(\tR\n" +
	"occurredAt\x12\x19\n" +
	"\bactor_id\x18\x03 \x01(\tR\aactorId\x12\x1f\n" +
	"\vactor_email\x18\x04 \x01(\tR\n" +
	"actorEmail\x12\x1b\n" +
	"\ttenant_id\x18\x05 \x01(\tR\btenantId\x12\x1f\n" +
	"\vtenant_name\x18\x06 \x01(\tR\n" +
	"tenantName\x12\x16\n" +
	"\x06action\x18\a \x01(\tR\x06action\x12\x16\n" +
	"\x06target\x18\b \x01(\tR\x06target\x12 \n" +
	"\vdescription\x18\t \x01(\tR\vdescription\"e\n" +
	"\x13AuditEventsResponse\x12-\n" +
	"\x06events\x18\x01 \x03(\v2\x15.clinks.v1.AuditEventR\x06events\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor2\xbd\b\n" +
	"\rClinksService\x12:\n" +
	"\x05Login\x12\x1d.clinks.v1.CredentialsRequest\x1a\x12.clinks.v1.Session\x12D\n" +
	"\x0fLoginSuperAdmin\x12\x1d.clinks.v1.CredentialsRequest\x1a\x12.clinks.v1.Session\x12:\n" +
	"\bRegister\x12\x1a.clinks.v1.RegisterRequest\x1a\x12.clinks.v1.Session\x12,\n" +
	"\x06Logout\x12\x10.clinks.v1.Empty\x1a\x10.clinks.v1.Empty\x122\n" +
	"\n" +
	"GetSession\x12\x10.clinks.v1.Empty\x1a\x12.clinks.v1.Session\x12B\n" +
	"\fSwitchTenant\x12\x1e.clinks.v1.SwitchTenantRequest\x1a\x12.clinks.v1.Session\x12M\n" +
	"\x10CreateInvitation\x12\".clinks.v1.CreateInvitationRequest\x1a\x15.clinks.v1.Invitation\x12J\n" +
	"\x10AcceptInvitation\x12\".clinks.v1.AcceptInvitationRequest\x1a\x12.clinks.v1.Session\x12>\n" +
	"\fGetLanguages\x12\x10.clinks.v1.Empty\x1a\x1c.clinks.v1.LanguagesResponse\x12U\n" +
	"\x0fGetTranslations\x12!.clinks.v1.GetTranslationsRequest\x1a\x1f.clinks.v1.TranslationsResponse\x12;\n" +
	"\vListTenants\x12\x10.clinks.v1.Empty\x1a\x1a.clinks.v1.TenantsResponse\x12A\n" +
	"\fCreateTenant\x12\x1e.clinks.v1.CreateTenantRequest\x1a\x11.clinks.v1.Tenant\x12F\n" +
	"\x14ListManagedLanguages\x12\x10.clinks.v1.Empty\x1a\x1c.clinks.v1.LanguagesResponse\x125\n" +
	"\fSaveLanguage\x12\x13.clinks.v1.Language\x1a\x10.clinks.v1.Empty\x12A\n" +
	"\x0fSaveTranslation\x12\x1c.clinks.v1.ScopedTranslation\x1a\x10.clinks.v1.Empty\x12T\n" +
	"\x0fListAuditEvents\x12!.clinks.v1.ListAuditEventsRequest\x1a\x1e.clinks.v1.AuditEventsResponseB@Z>github.com/besartmorina/clinks/server/proto/clinks/v1;clinksv1b\x06proto3"

var (
	file_clinks_v1_clinks_proto_rawDescOnce sync.Once
	file_clinks_v1_clinks_proto_rawDescData []byte
)

func file_clinks_v1_clinks_proto_rawDescGZIP() []byte {
	file_clinks_v1_clinks_proto_rawDescOnce.Do(func() {
		file_clinks_v1_clinks_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clinks_v1_clinks_proto_rawDesc), len(file_clinks_v1_clinks_proto_rawDesc)))
	})
	return file_clinks_v1_clinks_proto_rawDescData
}

var file_clinks_v1_clinks_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_clinks_v1_clinks_proto_goTypes = []any{
	(*Empty)(nil),                   // 0: clinks.v1.Empty
	(*CredentialsRequest)(nil),      // 1: clinks.v1.CredentialsRequest
	(*RegisterRequest)(nil),         // 2: clinks.v1.RegisterRequest
	(*SwitchTenantRequest)(nil),     // 3: clinks.v1.SwitchTenantRequest
	(*User)(nil),                    // 4: clinks.v1.User
	(*Tenant)(nil),                  // 5: clinks.v1.Tenant
	(*Membership)(nil),              // 6: clinks.v1.Membership
	(*Session)(nil),                 // 7: clinks.v1.Session
	(*CreateInvitationRequest)(nil), // 8: clinks.v1.CreateInvitationRequest
	(*Invitation)(nil),              // 9: clinks.v1.Invitation
	(*AcceptInvitationRequest)(nil), // 10: clinks.v1.AcceptInvitationRequest
	(*Language)(nil),                // 11: clinks.v1.Language
	(*LanguagesResponse)(nil),       // 12: clinks.v1.LanguagesResponse
	(*GetTranslationsRequest)(nil),  // 13: clinks.v1.GetTranslationsRequest
	(*ScopedTranslation)(nil),       // 14: clinks.v1.ScopedTranslation
	(*TranslationsResponse)(nil),    // 15: clinks.v1.TranslationsResponse
	(*TenantsResponse)(nil),         // 16: clinks.v1.TenantsResponse
	(*CreateTenantRequest)(nil),     // 17: clinks.v1.CreateTenantRequest
	(*ListAuditEventsRequest)(nil),  // 18: clinks.v1.ListAuditEventsRequest
	(*AuditEvent)(nil),              // 19: clinks.v1.AuditEvent
	(*AuditEventsResponse)(nil),     // 20: clinks.v1.AuditEventsResponse
}
var file_clinks_v1_clinks_proto_depIdxs = []int32{
	5,  // 0: clinks.v1.Membership.tenant:type_name -> clinks.v1.Tenant
	4,  // 1: clinks.v1.Session.user:type_name -> clinks.v1.User
	5,  // 2: clinks.v1.Session.active_tenant:type_name -> clinks.v1.Tenant
	6,  // 3: clinks.v1.Session.memberships:type_name -> clinks.v1.Membership
	11, // 4: clinks.v1.LanguagesResponse.languages:type_name -> clinks.v1.Language
	14, // 5: clinks.v1.TranslationsResponse.translations:type_name -> clinks.v1.ScopedTranslation
	5,  // 6: clinks.v1.TenantsResponse.tenants:type_name -> clinks.v1.Tenant
	19, // 7: clinks.v1.AuditEventsResponse.events:type_name -> clinks.v1.AuditEvent
	1,  // 8: clinks.v1.ClinksService.Login:input_type -> clinks.v1.CredentialsRequest
	1,  // 9: clinks.v1.ClinksService.LoginSuperAdmin:input_type -> clinks.v1.CredentialsRequest
	2,  // 10: clinks.v1.ClinksService.Register:input_type -> clinks.v1.RegisterRequest
	0,  // 11: clinks.v1.ClinksService.Logout:input_type -> clinks.v1.Empty
	0,  // 12: clinks.v1.ClinksService.GetSession:input_type -> clinks.v1.Empty
	3,  // 13: clinks.v1.ClinksService.SwitchTenant:input_type -> clinks.v1.SwitchTenantRequest
	8,  // 14: clinks.v1.ClinksService.CreateInvitation:input_type -> clinks.v1.CreateInvitationRequest
	10, // 15: clinks.v1.ClinksService.AcceptInvitation:input_type -> clinks.v1.AcceptInvitationRequest
	0,  // 16: clinks.v1.ClinksService.GetLanguages:input_type -> clinks.v1.Empty
	13, // 17: clinks.v1.ClinksService.GetTranslations:input_type -> clinks.v1.GetTranslationsRequest
	0,  // 18: clinks.v1.ClinksService.ListTenants:input_type -> clinks.v1.Empty
	17, // 19: clinks.v1.ClinksService.CreateTenant:input_type -> clinks.v1.CreateTenantRequest
	0,  // 20: clinks.v1.ClinksService.ListManagedLanguages:input_type -> clinks.v1.Empty
	11, // 21: clinks.v1.ClinksService.SaveLanguage:input_type -> clinks.v1.Language
	14, // 22: clinks.v1.ClinksService.SaveTranslation:input_type -> clinks.v1.ScopedTranslation
	18, // 23: clinks.v1.ClinksService.ListAuditEvents:input_type -> clinks.v1.ListAuditEventsRequest
	7,  // 24: clinks.v1.ClinksService.Login:output_type -> clinks.v1.Session
	7,  // 25: clinks.v1.ClinksService.LoginSuperAdmin:output_type -> clinks.v1.Session
	7,  // 26: clinks.v1.ClinksService.Register:output_type -> clinks.v1.Session
	0,  // 27: clinks.v1.ClinksService.Logout:output_type -> clinks.v1.Empty
	7,  // 28: clinks.v1.ClinksService.GetSession:output_type -> clinks.v1.Session
	7,  // 29: clinks.v1.ClinksService.SwitchTenant:output_type -> clinks.v1.Session
	9,  // 30: clinks.v1.ClinksService.CreateInvitation:output_type -> clinks.v1.Invitation
	7,  // 31: clinks.v1.ClinksService.AcceptInvitation:output_type -> clinks.v1.Session
	12, // 32: clinks.v1.ClinksService.GetLanguages:output_type -> clinks.v1.LanguagesResponse
	15, // 33: clinks.v1.ClinksService.GetTranslations:output_type -> clinks.v1.TranslationsResponse
	16, // 34: clinks.v1.ClinksService.ListTenants:output_type -> clinks.v1.TenantsResponse
	5,  // 35: clinks.v1.ClinksService.CreateTenant:output_type -> clinks.v1.Tenant
	12, // 36: clinks.v1.ClinksService.ListManagedLanguages:output_type -> clinks.v1.LanguagesResponse
	0,  // 37: clinks.v1.ClinksService.SaveLanguage:output_type -> clinks.v1.Empty
	0,  // 38: clinks.v1.ClinksService.SaveTranslation:output_type -> clinks.v1.Empty
	20, // 39: clinks.v1.ClinksService.ListAuditEvents:output_type -> clinks.v1.AuditEventsResponse
	24, // [24:40] is the sub-list for method output_type
	8,  // [8:24] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_clinks_v1_clinks_proto_init() }
func file_clinks_v1_clinks_proto_init() {
	if File_clinks_v1_clinks_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clinks_v1_clinks_proto_rawDesc), len(file_clinks_v1_clinks_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_clinks_v1_clinks_proto_goTypes,
		DependencyIndexes: file_clinks_v1_clinks_proto_depIdxs,
		MessageInfos:      file_clinks_v1_clinks_proto_msgTypes,
	}.Build()
	File_clinks_v1_clinks_proto = out.File
	file_clinks_v1_clinks_proto_goTypes = nil
	file_clinks_v1_clinks_proto_depIdxs = nil
}
